/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// Client->Server: 执行Data的操作请求
    /// </summary>
    public class C2SScriptActivityDataExecReq : ICsStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(C2SScriptActivityDataExecReq));

        public C2SScriptActivityDataExecReq()
        {
            ID = 0;
            DataEntryID = 0;
            Param1 = 0;
            Param2 = 0;
        }

        /// <summary>
        /// 活动ID
        /// </summary>
        public uint ID;

        /// <summary>
        /// ID
        /// </summary>
        public byte DataEntryID;

        /// <summary>
        /// 参数1
        /// </summary>
        public int Param1;

        /// <summary>
        /// 参数2
        /// </summary>
        public int Param2;

        public void WriteCs(IBuffer buffer)
        {
            buffer.WriteUInt32(ID, Endianness.Big);
            buffer.WriteByte(DataEntryID);
            buffer.WriteInt32(Param1, Endianness.Big);
            buffer.WriteInt32(Param2, Endianness.Big);
        }

        public void ReadCs(IBuffer buffer)
        {
            ID = buffer.ReadUInt32(Endianness.Big);
            DataEntryID = buffer.ReadByte();
            Param1 = buffer.ReadInt32(Endianness.Big);
            Param2 = buffer.ReadInt32(Endianness.Big);
        }

    }
}
