/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Constant;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 通知客户端系统提示
    /// </summary>
    public class CSChatSystemMsgNtf : NoticeMsg
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSChatSystemMsgNtf));

        public CSChatSystemMsgNtf()
        {
            MsgType = 0;
            MsgArea = 0;
            Dbid = 0;
            MsgParamNum = 0;
            MsgPramList = new CSMsgParam[CsProtoConstant.CS_CHAT_SYSTEM_MSG_PARAM_NUM];
            for (int i = 0; i < CsProtoConstant.CS_CHAT_SYSTEM_MSG_PARAM_NUM; i++)
            {
                MsgPramList[i] = new CSMsgParam(null);
            }
            Items = new List<byte>();
        }

        /// <summary>
        /// MessageList.xlsx配置项
        /// </summary>
        public uint MsgType;

        /// <summary>
        /// 通知区域（个人/全服/...）
        /// </summary>
        public uint MsgArea;

        /// <summary>
        /// 玩家dbid
        /// </summary>
        public ulong Dbid;

        /// <summary>
        /// 参数数量
        /// </summary>
        public byte MsgParamNum;

        /// <summary>
        /// 参数列表
        /// </summary>
        public CSMsgParam[] MsgPramList;

        /// <summary>
        /// 聊天道具数据
        /// </summary>
        public List<byte> Items;

        public void WriteCs(IBuffer buffer)
        {
            buffer.WriteUInt32(MsgType, Endianness.Big);
            buffer.WriteUInt32(MsgArea, Endianness.Big);
            buffer.WriteUInt64(Dbid, Endianness.Big);
            buffer.WriteByte(MsgParamNum);
            for (int i = 0; i < CsProtoConstant.CS_CHAT_SYSTEM_MSG_PARAM_NUM; i++)
            {
                MsgPramList[i].WriteCs(buffer);
            }
            int itemsCount = (int)Items.Count;
            buffer.WriteInt32(itemsCount, Endianness.Big);
            for (int i = 0; i < itemsCount; i++)
            {
                buffer.WriteByte(Items[i]);
            }
        }

        public void ReadCs(IBuffer buffer)
        {
            MsgType = buffer.ReadUInt32(Endianness.Big);
            MsgArea = buffer.ReadUInt32(Endianness.Big);
            Dbid = buffer.ReadUInt64(Endianness.Big);
            MsgParamNum = buffer.ReadByte();
            for (int i = 0; i < CsProtoConstant.CS_CHAT_SYSTEM_MSG_PARAM_NUM; i++)
            {
                MsgPramList[i].ReadCs(buffer);
            }
            Items.Clear();
            int itemsCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < itemsCount; i++)
            {
                byte ItemsEntry = buffer.ReadByte();
                Items.Add(ItemsEntry);
            }
        }

    }
}
