/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 怪物物理部位信息
    /// </summary>
    public class CSMonsterPhysPartInfo : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSMonsterPhysPartInfo));

        public CSMonsterPhysPartInfo()
        {
            MonsterID = 0;
            EntityPose = new CSQuatT();
            PartPose = new List<CSQuatT>();
        }

        /// <summary>
        /// 怪物ID
        /// </summary>
        public uint MonsterID;

        /// <summary>
        /// 怪物位置朝向
        /// </summary>
        public CSQuatT EntityPose;

        /// <summary>
        /// 物理部位位置列表
        /// </summary>
        public List<CSQuatT> PartPose;

        public void Write(IBuffer buffer)
        {
            buffer.WriteUInt32(MonsterID, Endianness.Big);
            EntityPose.Write(buffer);
            uint partPoseCount = (uint)PartPose.Count;
            buffer.WriteUInt32(partPoseCount, Endianness.Big);
            for (int i = 0; i < partPoseCount; i++)
            {
                PartPose[i].Write(buffer);
            }
        }

        public void Read(IBuffer buffer)
        {
            MonsterID = buffer.ReadUInt32(Endianness.Big);
            EntityPose.Read(buffer);
            PartPose.Clear();
            uint partPoseCount = buffer.ReadUInt32(Endianness.Big);
            for (int i = 0; i < partPoseCount; i++)
            {
                CSQuatT PartPoseEntry = new CSQuatT();
                PartPoseEntry.Read(buffer);
                PartPose.Add(PartPoseEntry);
            }
        }

    }
}
