/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;
using Arrowgene.MonsterHunterOnline.Service.System.ItemSystem;
using Arrowgene.MonsterHunterOnline.Service.Tdr.TlvStructures;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 卖出背包中的物品的返回
    /// </summary>
    public class CSNpcShopSellItemRsp : ICsStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSNpcShopSellItemRsp));

        public CSNpcShopSellItemRsp()
        {
            Ret = 0;
            ItemType = 0;
            ItemCount = 0;
            MoneyAdd = 0;
            ItemData = new Item();
        }

        /// <summary>
        /// 返回值，0为成功
        /// </summary>
        public int Ret;

        /// <summary>
        /// 卖出的物品类型
        /// </summary>
        public int ItemType;

        /// <summary>
        /// 卖出的物品数量
        /// </summary>
        public int ItemCount;

        /// <summary>
        /// 获得的金币
        /// </summary>
        public int MoneyAdd;

        /// <summary>
        /// 道具数据
        /// </summary>
        public Item ItemData;

        public void WriteCs(IBuffer buffer)
        {
            buffer.WriteInt32(Ret, Endianness.Big);
            buffer.WriteInt32(ItemType, Endianness.Big);
            buffer.WriteInt32(ItemCount, Endianness.Big);
            buffer.WriteInt32(MoneyAdd, Endianness.Big);
            ItemData.WriteTlv(buffer);
        }

        public void ReadCs(IBuffer buffer)
        {
            Ret = buffer.ReadInt32(Endianness.Big);
            ItemType = buffer.ReadInt32(Endianness.Big);
            ItemCount = buffer.ReadInt32(Endianness.Big);
            MoneyAdd = buffer.ReadInt32(Endianness.Big);
            ItemData.ReadTlv(buffer);
        }

    }
}
