/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 申请缴纳请求
    /// </summary>
    public class CSPaidContributeBoxRsp : ICsStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSPaidContributeBoxRsp));

        public CSPaidContributeBoxRsp()
        {
            ErrCode = 0;
            NetID = 0;
            PaidItems = new List<CSPaidContributeBoxData>();
            PaidBuffs = new List<CSPaidContributeBoxData>();
        }

        /// <summary>
        /// 错误码
        /// </summary>
        public int ErrCode;

        /// <summary>
        /// 玩家ID
        /// </summary>
        public int NetID;

        /// <summary>
        /// 缴纳物品组
        /// </summary>
        public List<CSPaidContributeBoxData> PaidItems;

        /// <summary>
        /// 缴纳BUFF组
        /// </summary>
        public List<CSPaidContributeBoxData> PaidBuffs;

        public void WriteCs(IBuffer buffer)
        {
            buffer.WriteInt32(ErrCode, Endianness.Big);
            buffer.WriteInt32(NetID, Endianness.Big);
            int paidItemsCount = (int)PaidItems.Count;
            buffer.WriteInt32(paidItemsCount, Endianness.Big);
            for (int i = 0; i < paidItemsCount; i++)
            {
                PaidItems[i].WriteCs(buffer);
            }
            int paidBuffsCount = (int)PaidBuffs.Count;
            buffer.WriteInt32(paidBuffsCount, Endianness.Big);
            for (int i = 0; i < paidBuffsCount; i++)
            {
                PaidBuffs[i].WriteCs(buffer);
            }
        }

        public void ReadCs(IBuffer buffer)
        {
            ErrCode = buffer.ReadInt32(Endianness.Big);
            NetID = buffer.ReadInt32(Endianness.Big);
            PaidItems.Clear();
            int paidItemsCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < paidItemsCount; i++)
            {
                CSPaidContributeBoxData PaidItemsEntry = new CSPaidContributeBoxData();
                PaidItemsEntry.ReadCs(buffer);
                PaidItems.Add(PaidItemsEntry);
            }
            PaidBuffs.Clear();
            int paidBuffsCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < paidBuffsCount; i++)
            {
                CSPaidContributeBoxData PaidBuffsEntry = new CSPaidContributeBoxData();
                PaidBuffsEntry.ReadCs(buffer);
                PaidBuffs.Add(PaidBuffsEntry);
            }
        }

    }
}
