/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 玩家换区状态通知
    /// </summary>
    public class CSPlayerRegionJumpRsp : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSPlayerRegionJumpRsp));

        public CSPlayerRegionJumpRsp()
        {
            ErrorCode = 0;
            RegionId = 0;
            Transform = new CSQuatT();
        }

        /// <summary>
        /// 换区反馈错误编号
        /// </summary>
        public int ErrorCode;

        /// <summary>
        /// 换区后玩家当前所在区编号
        /// </summary>
        public int RegionId;

        /// <summary>
        /// 换区后玩家当前所在区位置和朝向
        /// </summary>
        public CSQuatT Transform;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(ErrorCode, Endianness.Big);
            buffer.WriteInt32(RegionId, Endianness.Big);
            Transform.Write(buffer);
        }

        public void Read(IBuffer buffer)
        {
            ErrorCode = buffer.ReadInt32(Endianness.Big);
            RegionId = buffer.ReadInt32(Endianness.Big);
            Transform.Read(buffer);
        }

    }
}
