/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Constant;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 客户端角色创建信息
    /// </summary>
    public class CSRoleCreateInfo : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSRoleCreateInfo));

        public CSRoleCreateInfo()
        {
            Name = "";
            Gender = 0;
            FaceId = 0;
            HairId = 0;
            UnderclothesId = 0;
            SkinColor = 0;
            HairColor = 0;
            InnerColor = 0;
            EyeBall = 0;
            EyeColor = 0;
            FaceTattooIndex = 0;
            FaceTattooColor = 0;
            FacialInfo = new short[CsProtoConstant.CS_MAX_FACIALINFO_COUNT];
            DBID = 0;
        }

        /// <summary>
        /// 角色名
        /// </summary>
        public string Name;

        /// <summary>
        /// 角色性别
        /// </summary>
        public byte Gender;

        /// <summary>
        /// 脸型ID
        /// </summary>
        public ushort FaceId;

        /// <summary>
        /// 发型ID
        /// </summary>
        public ushort HairId;

        /// <summary>
        /// 内衣ID
        /// </summary>
        public ushort UnderclothesId;

        /// <summary>
        /// 皮肤颜色
        /// </summary>
        public int SkinColor;

        /// <summary>
        /// 头发颜色
        /// </summary>
        public int HairColor;

        /// <summary>
        /// 内衣颜色
        /// </summary>
        public int InnerColor;

        /// <summary>
        /// 眼睛
        /// </summary>
        public int EyeBall;

        /// <summary>
        /// 眼睛颜色
        /// </summary>
        public int EyeColor;

        /// <summary>
        /// 脸部贴花
        /// </summary>
        public int FaceTattooIndex;

        /// <summary>
        /// 脸部贴花颜色
        /// </summary>
        public int FaceTattooColor;

        /// <summary>
        /// 捏脸数据集合
        /// </summary>
        public short[] FacialInfo;

        /// <summary>
        /// DBID,客户端不必填写,从NameSvr返回后查找
        /// </summary>
        public ulong DBID;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(Name.Length + 1, Endianness.Big);
            buffer.WriteCString(Name);
            buffer.WriteByte(Gender);
            buffer.WriteUInt16(FaceId, Endianness.Big);
            buffer.WriteUInt16(HairId, Endianness.Big);
            buffer.WriteUInt16(UnderclothesId, Endianness.Big);
            buffer.WriteInt32(SkinColor, Endianness.Big);
            buffer.WriteInt32(HairColor, Endianness.Big);
            buffer.WriteInt32(InnerColor, Endianness.Big);
            buffer.WriteInt32(EyeBall, Endianness.Big);
            buffer.WriteInt32(EyeColor, Endianness.Big);
            buffer.WriteInt32(FaceTattooIndex, Endianness.Big);
            buffer.WriteInt32(FaceTattooColor, Endianness.Big);
            for (int i = 0; i < CsProtoConstant.CS_MAX_FACIALINFO_COUNT; i++)
            {
                buffer.WriteInt16(FacialInfo[i], Endianness.Big);
            }
            buffer.WriteUInt64(DBID, Endianness.Big);
        }

        public void Read(IBuffer buffer)
        {
            int NameEntryLen = buffer.ReadInt32(Endianness.Big);
            Name = buffer.ReadString(NameEntryLen);
            Gender = buffer.ReadByte();
            FaceId = buffer.ReadUInt16(Endianness.Big);
            HairId = buffer.ReadUInt16(Endianness.Big);
            UnderclothesId = buffer.ReadUInt16(Endianness.Big);
            SkinColor = buffer.ReadInt32(Endianness.Big);
            HairColor = buffer.ReadInt32(Endianness.Big);
            InnerColor = buffer.ReadInt32(Endianness.Big);
            EyeBall = buffer.ReadInt32(Endianness.Big);
            EyeColor = buffer.ReadInt32(Endianness.Big);
            FaceTattooIndex = buffer.ReadInt32(Endianness.Big);
            FaceTattooColor = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < CsProtoConstant.CS_MAX_FACIALINFO_COUNT; i++)
            {
                FacialInfo[i] = buffer.ReadInt16(Endianness.Big);
            }
            DBID = buffer.ReadUInt64(Endianness.Big);
        }

    }
}
