/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 可选礼包开包内容
    /// </summary>
    public class CSSelectItemBoxOpenBoxNtf : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSSelectItemBoxOpenBoxNtf));

        public CSSelectItemBoxOpenBoxNtf()
        {
            Box = 0;
            ItemList = new List<CSItemBoxItemEntry>();
            EquipList = new List<ItemData>();
        }

        /// <summary>
        /// 宝箱ID
        /// </summary>
        public int Box;

        /// <summary>
        /// 物品列表
        /// </summary>
        public List<CSItemBoxItemEntry> ItemList;

        /// <summary>
        /// 装备列表
        /// </summary>
        public List<ItemData> EquipList;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(Box, Endianness.Big);
            byte itemListCount = (byte)ItemList.Count;
            buffer.WriteByte(itemListCount);
            for (int i = 0; i < itemListCount; i++)
            {
                ItemList[i].Write(buffer);
            }
            byte equipListCount = (byte)EquipList.Count;
            buffer.WriteByte(equipListCount);
            for (int i = 0; i < equipListCount; i++)
            {
                EquipList[i].Write(buffer);
            }
        }

        public void Read(IBuffer buffer)
        {
            Box = buffer.ReadInt32(Endianness.Big);
            ItemList.Clear();
            byte itemListCount = buffer.ReadByte();
            for (int i = 0; i < itemListCount; i++)
            {
                CSItemBoxItemEntry ItemListEntry = new CSItemBoxItemEntry();
                ItemListEntry.Read(buffer);
                ItemList.Add(ItemListEntry);
            }
            EquipList.Clear();
            byte equipListCount = buffer.ReadByte();
            for (int i = 0; i < equipListCount; i++)
            {
                ItemData EquipListEntry = new ItemData();
                EquipListEntry.Read(buffer);
                EquipList.Add(EquipListEntry);
            }
        }

    }
}
