/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 队员入队后，同步队员身上buff
    /// </summary>
    public class CSTeamMemberBuffSync : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSTeamMemberBuffSync));

        public CSTeamMemberBuffSync()
        {
            TeamId = 0;
            member = new List<CSTeamMemIconBuffs>();
        }

        /// <summary>
        /// 队伍唯一标识ID
        /// </summary>
        public uint TeamId;

        /// <summary>
        /// 队员IconBuff信息
        /// </summary>
        public List<CSTeamMemIconBuffs> member;

        public void Write(IBuffer buffer)
        {
            buffer.WriteUInt32(TeamId, Endianness.Big);
            int memberCount = (int)member.Count;
            buffer.WriteInt32(memberCount, Endianness.Big);
            for (int i = 0; i < memberCount; i++)
            {
                member[i].Write(buffer);
            }
        }

        public void Read(IBuffer buffer)
        {
            TeamId = buffer.ReadUInt32(Endianness.Big);
            member.Clear();
            int memberCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < memberCount; i++)
            {
                CSTeamMemIconBuffs memberEntry = new CSTeamMemIconBuffs();
                memberEntry.Read(buffer);
                member.Add(memberEntry);
            }
        }

    }
}
