/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    public class CSTowerMemberInfo : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSTowerMemberInfo));

        public CSTowerMemberInfo()
        {
            PlayerNetID = 0;
            Attack = 0;
            Defense = 0;
            RoleName = "";
            BestHistoryTime = 0;
        }

        /// <summary>
        /// 玩家ID
        /// </summary>
        public int PlayerNetID;

        /// <summary>
        /// 伤害输入
        /// </summary>
        public int Attack;

        /// <summary>
        /// 承受伤害
        /// </summary>
        public int Defense;

        public string RoleName;

        /// <summary>
        /// 历史最好消耗时间秒
        /// </summary>
        public int BestHistoryTime;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(PlayerNetID, Endianness.Big);
            buffer.WriteInt32(Attack, Endianness.Big);
            buffer.WriteInt32(Defense, Endianness.Big);
            buffer.WriteInt32(RoleName.Length + 1, Endianness.Big);
            buffer.WriteCString(RoleName);
            buffer.WriteInt32(BestHistoryTime, Endianness.Big);
        }

        public void Read(IBuffer buffer)
        {
            PlayerNetID = buffer.ReadInt32(Endianness.Big);
            Attack = buffer.ReadInt32(Endianness.Big);
            Defense = buffer.ReadInt32(Endianness.Big);
            int RoleNameEntryLen = buffer.ReadInt32(Endianness.Big);
            RoleName = buffer.ReadString(RoleNameEntryLen);
            BestHistoryTime = buffer.ReadInt32(Endianness.Big);
        }

    }
}
