/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 委托小组奖励领取记录
    /// </summary>
    public class PlayerLevelEnstrustRewardInfo : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(PlayerLevelEnstrustRewardInfo));

        public PlayerLevelEnstrustRewardInfo()
        {
            EnSubGroupID = 0;
            State = 0;
        }

        /// <summary>
        /// 小组ID
        /// </summary>
        public int EnSubGroupID;

        /// <summary>
        /// 1表示已经领取过，0表示没有领取过
        /// </summary>
        public byte State;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(EnSubGroupID, Endianness.Big);
            buffer.WriteByte(State);
        }

        public void Read(IBuffer buffer)
        {
            EnSubGroupID = buffer.ReadInt32(Endianness.Big);
            State = buffer.ReadByte();
        }

    }
}
