/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 返回指定雕像数据
    /// </summary>
    public class S2CGetSculpture : ICsStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(S2CGetSculpture));

        public S2CGetSculpture()
        {
            Round = 0;
            Current = new List<CSSculptureObj>();
            Best = new CSSculptureHistory();
            History = new List<CSSculptureHistory>();
        }

        /// <summary>
        /// 轮次
        /// </summary>
        public int Round;

        /// <summary>
        /// 当期数据
        /// </summary>
        public List<CSSculptureObj> Current;

        /// <summary>
        /// 历史最佳
        /// </summary>
        public CSSculptureHistory Best;

        /// <summary>
        /// 历史数据
        /// </summary>
        public List<CSSculptureHistory> History;

        public void WriteCs(IBuffer buffer)
        {
            buffer.WriteInt32(Round, Endianness.Big);
            int currentCount = (int)Current.Count;
            buffer.WriteInt32(currentCount, Endianness.Big);
            for (int i = 0; i < currentCount; i++)
            {
                Current[i].WriteCs(buffer);
            }
            Best.WriteCs(buffer);
            int historyCount = (int)History.Count;
            buffer.WriteInt32(historyCount, Endianness.Big);
            for (int i = 0; i < historyCount; i++)
            {
                History[i].WriteCs(buffer);
            }
        }

        public void ReadCs(IBuffer buffer)
        {
            Round = buffer.ReadInt32(Endianness.Big);
            Current.Clear();
            int currentCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < currentCount; i++)
            {
                CSSculptureObj CurrentEntry = new CSSculptureObj();
                CurrentEntry.ReadCs(buffer);
                Current.Add(CurrentEntry);
            }
            Best.ReadCs(buffer);
            History.Clear();
            int historyCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < historyCount; i++)
            {
                CSSculptureHistory HistoryEntry = new CSSculptureHistory();
                HistoryEntry.ReadCs(buffer);
                History.Add(HistoryEntry);
            }
        }

    }
}
