/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 特殊奖励关卡信息
    /// </summary>
    public class S2CHubSpecRewardLevelNtf : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(S2CHubSpecRewardLevelNtf));

        public S2CHubSpecRewardLevelNtf()
        {
            HubEntryID = 0;
            LevelID = 0;
            LevelTryCnt = 0;
            TotalLeftCnt = 0;
            NextRefreshSec = 0;
        }

        /// <summary>
        /// hub ID
        /// </summary>
        public int HubEntryID;

        /// <summary>
        /// 当前特殊奖励关卡ID
        /// </summary>
        public int LevelID;

        /// <summary>
        /// 当天进入当前关卡的次数
        /// </summary>
        public int LevelTryCnt;

        /// <summary>
        /// 当天剩余进入次数
        /// </summary>
        public int TotalLeftCnt;

        /// <summary>
        /// 距离下一次刷新的时间秒
        /// </summary>
        public int NextRefreshSec;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(HubEntryID, Endianness.Big);
            buffer.WriteInt32(LevelID, Endianness.Big);
            buffer.WriteInt32(LevelTryCnt, Endianness.Big);
            buffer.WriteInt32(TotalLeftCnt, Endianness.Big);
            buffer.WriteInt32(NextRefreshSec, Endianness.Big);
        }

        public void Read(IBuffer buffer)
        {
            HubEntryID = buffer.ReadInt32(Endianness.Big);
            LevelID = buffer.ReadInt32(Endianness.Big);
            LevelTryCnt = buffer.ReadInt32(Endianness.Big);
            TotalLeftCnt = buffer.ReadInt32(Endianness.Big);
            NextRefreshSec = buffer.ReadInt32(Endianness.Big);
        }

    }
}
