/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 个人阶段奖励请求回复
    /// </summary>
    public class S2CLeagueStepReward : ICsStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(S2CLeagueStepReward));

        public S2CLeagueStepReward()
        {
            Level = 0;
            WeekLimit = 0;
            TotalLimit = 0;
        }

        /// <summary>
        /// 奖励的等级
        /// </summary>
        public int Level;

        /// <summary>
        /// 荣誉勋章达到周上限
        /// </summary>
        public byte WeekLimit;

        /// <summary>
        /// 荣誉勋章达到总上限
        /// </summary>
        public byte TotalLimit;

        public void WriteCs(IBuffer buffer)
        {
            buffer.WriteInt32(Level, Endianness.Big);
            buffer.WriteByte(WeekLimit);
            buffer.WriteByte(TotalLimit);
        }

        public void ReadCs(IBuffer buffer)
        {
            Level = buffer.ReadInt32(Endianness.Big);
            WeekLimit = buffer.ReadByte();
            TotalLimit = buffer.ReadByte();
        }

    }
}
