/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 获取修罗试练最短通关时间
    /// </summary>
    public class SCDemonTrialGetLevelPassTimeRsp : ICsStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(SCDemonTrialGetLevelPassTimeRsp));

        public SCDemonTrialGetLevelPassTimeRsp()
        {
            ErrCode = 0;
            PassLevelInfo = new List<CSLevelPassMinTime>();
        }

        /// <summary>
        /// 错误码
        /// </summary>
        public int ErrCode;

        /// <summary>
        /// 关卡通关信息
        /// </summary>
        public List<CSLevelPassMinTime> PassLevelInfo;

        public void WriteCs(IBuffer buffer)
        {
            buffer.WriteInt32(ErrCode, Endianness.Big);
            int passLevelInfoCount = (int)PassLevelInfo.Count;
            buffer.WriteInt32(passLevelInfoCount, Endianness.Big);
            for (int i = 0; i < passLevelInfoCount; i++)
            {
                PassLevelInfo[i].WriteCs(buffer);
            }
        }

        public void ReadCs(IBuffer buffer)
        {
            ErrCode = buffer.ReadInt32(Endianness.Big);
            PassLevelInfo.Clear();
            int passLevelInfoCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < passLevelInfoCount; i++)
            {
                CSLevelPassMinTime PassLevelInfoEntry = new CSLevelPassMinTime();
                PassLevelInfoEntry.ReadCs(buffer);
                PassLevelInfo.Add(PassLevelInfoEntry);
            }
        }

    }
}
