/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 玫瑰礼花通知
    /// </summary>
    public class SCRoseFlowerNtf : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(SCRoseFlowerNtf));

        public SCRoseFlowerNtf()
        {
            FromName = "";
            FromID = 0;
            TargetName = "";
            TargetID = 0;
            RoseType = 0;
            AddValue = 0;
        }

        /// <summary>
        /// 赠送者
        /// </summary>
        public string FromName;

        /// <summary>
        /// 请求者ID
        /// </summary>
        public ulong FromID;

        /// <summary>
        /// 被赠送者
        /// </summary>
        public string TargetName;

        /// <summary>
        /// 被赠送者ID
        /// </summary>
        public ulong TargetID;

        /// <summary>
        /// 玫瑰类型
        /// </summary>
        public int RoseType;

        /// <summary>
        /// 友好度添加
        /// </summary>
        public int AddValue;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(FromName.Length + 1, Endianness.Big);
            buffer.WriteCString(FromName);
            buffer.WriteUInt64(FromID, Endianness.Big);
            buffer.WriteInt32(TargetName.Length + 1, Endianness.Big);
            buffer.WriteCString(TargetName);
            buffer.WriteUInt64(TargetID, Endianness.Big);
            buffer.WriteInt32(RoseType, Endianness.Big);
            buffer.WriteInt32(AddValue, Endianness.Big);
        }

        public void Read(IBuffer buffer)
        {
            int FromNameEntryLen = buffer.ReadInt32(Endianness.Big);
            FromName = buffer.ReadString(FromNameEntryLen);
            FromID = buffer.ReadUInt64(Endianness.Big);
            int TargetNameEntryLen = buffer.ReadInt32(Endianness.Big);
            TargetName = buffer.ReadString(TargetNameEntryLen);
            TargetID = buffer.ReadUInt64(Endianness.Big);
            RoseType = buffer.ReadInt32(Endianness.Big);
            AddValue = buffer.ReadInt32(Endianness.Big);
        }

    }
}
