/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Enums
{
    public enum CS_PLAYER_EXT_TYPE
    {
        /// <summary>
        /// 交互管理;base_class=CPlayerInteractBase
        /// </summary>
        CS_PLAYER_EXT_INTERACT = 2,

        /// <summary>
        /// 新手引导;base_class=CPlayerGuideBase;init_data=GuideSteps;other_data=astGuideSteps
        /// </summary>
        CS_PLAYER_EXT_GUIDE = 3,

        /// <summary>
        /// 客户端配置;base_class=CPlayerClientSettingsBase;init_data=ClientSettings;other_data=stClientSettings
        /// </summary>
        CS_PLAYER_EXT_CLIENT_SETTINGS = 4,

    }
}
