/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Enums
{
    public enum ROMTE_DATA_TYPE
    {
        /// <summary>
        /// 道具加载数据
        /// </summary>
        ITEMMGR_DATA_TYPE = 1,

        /// <summary>
        /// 关卡数据类型
        /// </summary>
        LEVELINFO_DATA_TYPE = 2,

        /// <summary>
        /// 猎人之星数据类型
        /// </summary>
        HUNTERSTAR_DATA_TYPE = 3,

        /// <summary>
        /// 任务数据类型
        /// </summary>
        TASKSYS_DATA_TYPE = 4,

        /// <summary>
        /// 普通限制数据
        /// </summary>
        NORMAL_LIMIT_DATATYPE = 5,

        /// <summary>
        /// 补给方案数据
        /// </summary>
        SUPPLY_PLAN_DATA_TYPE = 6,

    }
}
