/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Enums
{
    public enum TeamModifyRet
    {
        /// <summary>
        /// 成功
        /// </summary>
        TEAMMODIFYRET_OK = 0,

        /// <summary>
        /// 含有屏蔽字
        /// </summary>
        TEAMMODIFYRET_HASINVALIDCHARS = 1,

        /// <summary>
        /// 等级范围非法
        /// </summary>
        TEAMMODIFYRET_INVALIDLEVELRANGE = 2,

        /// <summary>
        /// 最大队员数量非法
        /// </summary>
        TEAMMODIFYRET_INVALIDMEMBERMAX = 3,

    }
}
