/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// hit信息用于统计
    /// </summary>
    public class CSActorHitDebuginfo : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSActorHitDebuginfo));

        public CSActorHitDebuginfo()
        {
            AttackerNetObjId = 0;
            TargetNetObjId = 0;
            StateID = 0;
        }

        /// <summary>
        /// Attacker的NetObjId
        /// </summary>
        public uint AttackerNetObjId;

        /// <summary>
        /// Target的NetObjId
        /// </summary>
        public uint TargetNetObjId;

        /// <summary>
        /// StateID
        /// </summary>
        public int StateID;

        public void Write(IBuffer buffer)
        {
            buffer.WriteUInt32(AttackerNetObjId, Endianness.Big);
            buffer.WriteUInt32(TargetNetObjId, Endianness.Big);
            buffer.WriteInt32(StateID, Endianness.Big);
        }

        public void Read(IBuffer buffer)
        {
            AttackerNetObjId = buffer.ReadUInt32(Endianness.Big);
            TargetNetObjId = buffer.ReadUInt32(Endianness.Big);
            StateID = buffer.ReadInt32(Endianness.Big);
        }

    }
}
