/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 副本操作逻辑响应
    /// </summary>
    public class CSBSMRoomOperRsp : IStructure
    {

        public CSBSMRoomOperRsp()
        {
            Ret = 0;
            OpNetID = 0;
            RoleName = "";
            OpCmd = 0;
            Param1 = 0;
            Param2 = 0;
            Param3 = 0;
            Param4 = 0;
            Param5 = 0;
        }

        /// <summary>
        /// 错误码
        /// </summary>
        public int Ret;

        /// <summary>
        /// 操作者
        /// </summary>
        public int OpNetID;

        public string RoleName;

        /// <summary>
        /// 操作类型
        /// </summary>
        public int OpCmd;

        /// <summary>
        /// 操作参数1
        /// </summary>
        public uint Param1;

        /// <summary>
        /// 操作参数1
        /// </summary>
        public uint Param2;

        /// <summary>
        /// 操作参数1
        /// </summary>
        public uint Param3;

        /// <summary>
        /// 操作参数1
        /// </summary>
        public uint Param4;

        /// <summary>
        /// 操作参数1
        /// </summary>
        public uint Param5;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(Ret, Endianness.Big);
            buffer.WriteInt32(OpNetID, Endianness.Big);
            buffer.WriteInt32(RoleName.Length + 1, Endianness.Big);
            buffer.WriteCString(RoleName);
            buffer.WriteInt32(OpCmd, Endianness.Big);
            buffer.WriteUInt32(Param1, Endianness.Big);
            buffer.WriteUInt32(Param2, Endianness.Big);
            buffer.WriteUInt32(Param3, Endianness.Big);
            buffer.WriteUInt32(Param4, Endianness.Big);
            buffer.WriteUInt32(Param5, Endianness.Big);
        }

    }
}
