/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 猫猫宝藏
    /// </summary>
    public class CSCatTreatureInfo : IStructure
    {

        public CSCatTreatureInfo()
        {
            tCatTime = 0;
            vOpenInfo = new byte[CsProtoConstant.CS_CAT_TREATURE_MAX_CNT];
            iTools = 0;
            iOpenID = 0;
        }

        /// <summary>
        /// 宝藏周期
        /// </summary>
        public long tCatTime;

        /// <summary>
        /// 已开启的宝藏信息
        /// </summary>
        public byte[] vOpenInfo;

        /// <summary>
        /// 工具数量
        /// </summary>
        public byte iTools;

        /// <summary>
        /// 开启
        /// </summary>
        public byte iOpenID;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt64(tCatTime, Endianness.Big);
            for (int i = 0; i < CsProtoConstant.CS_CAT_TREATURE_MAX_CNT; i++)
            {
                buffer.WriteByte(vOpenInfo[i]);
            }
            buffer.WriteByte(iTools);
            buffer.WriteByte(iOpenID);
        }

    }
}
