/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 聊天发送的道具信息
    /// </summary>
    public class CsChatItems : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CsChatItems));

        public CsChatItems()
        {
            Items = new List<CsChatItem>();
        }

        /// <summary>
        /// 聊天道具数据
        /// </summary>
        public List<CsChatItem> Items;

        public void Write(IBuffer buffer)
        {
            uint itemsCount = (uint)Items.Count;
            buffer.WriteUInt32(itemsCount, Endianness.Big);
            for (int i = 0; i < itemsCount; i++)
            {
                Items[i].Write(buffer);
            }
        }

        public void Read(IBuffer buffer)
        {
            Items.Clear();
            uint itemsCount = buffer.ReadUInt32(Endianness.Big);
            for (int i = 0; i < itemsCount; i++)
            {
                CsChatItem ItemsEntry = new CsChatItem();
                ItemsEntry.Read(buffer);
                Items.Add(ItemsEntry);
            }
        }

    }
}
