/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 刷新数字确认
    /// </summary>
    public class CSDragonBoxNumOKRsp : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSDragonBoxNumOKRsp));

        public CSDragonBoxNumOKRsp()
        {
            BoxID = 0;
            sucess = 0;
            Number = 0;
        }

        /// <summary>
        /// 箱子ID
        /// </summary>
        public int BoxID;

        /// <summary>
        /// 0成功1失败
        /// </summary>
        public int sucess;

        /// <summary>
        /// 数字
        /// </summary>
        public int Number;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(BoxID, Endianness.Big);
            buffer.WriteInt32(sucess, Endianness.Big);
            buffer.WriteInt32(Number, Endianness.Big);
        }

        public void Read(IBuffer buffer)
        {
            BoxID = buffer.ReadInt32(Endianness.Big);
            sucess = buffer.ReadInt32(Endianness.Big);
            Number = buffer.ReadInt32(Endianness.Big);
        }

    }
}
