/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 装备直升请求
    /// </summary>
    public class CSEquipQuickUpgradeReq : IStructure
    {

        public CSEquipQuickUpgradeReq()
        {
            CostItem = new CSItemArgs();
            Equip = new CSItemArgs();
            Route = new List<CSEquipUpgradeRoute>();
        }

        /// <summary>
        /// 消耗直升券
        /// </summary>
        public CSItemArgs CostItem;

        /// <summary>
        /// 待升级的装备
        /// </summary>
        public CSItemArgs Equip;

        /// <summary>
        /// 升级路线
        /// </summary>
        public List<CSEquipUpgradeRoute> Route;

        public void Write(IBuffer buffer)
        {
            CostItem.Write(buffer);
            Equip.Write(buffer);
            int routeCount = (int)Route.Count;
            buffer.WriteInt32(routeCount, Endianness.Big);
            for (int i = 0; i < routeCount; i++)
            {
                Route[i].Write(buffer);
            }
        }

    }
}
