/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 精粹相应
    /// </summary>
    public class CSEquipQuenchRsp : IStructure
    {

        public CSEquipQuenchRsp()
        {
            RetCode = 0;
            ItemUid = 0;
            QuenchLv = 0;
            AttrType = new List<int>();
            AttrValue = new List<byte>();
        }

        /// <summary>
        /// 状态码
        /// </summary>
        public int RetCode;

        /// <summary>
        /// 装备唯一ID
        /// </summary>
        public long ItemUid;

        /// <summary>
        /// pre等级
        /// </summary>
        public int QuenchLv;

        /// <summary>
        /// 精粹属性类型
        /// </summary>
        public List<int> AttrType;

        /// <summary>
        /// 精粹属性值
        /// </summary>
        public List<byte> AttrValue;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(RetCode, Endianness.Big);
            buffer.WriteInt64(ItemUid, Endianness.Big);
            buffer.WriteInt32(QuenchLv, Endianness.Big);
            int attrTypeCount = (int)AttrType.Count;
            buffer.WriteInt32(attrTypeCount, Endianness.Big);
            for (int i = 0; i < attrTypeCount; i++)
            {
                buffer.WriteInt32(AttrType[i], Endianness.Big);
            }
            int attrValueCount = (int)AttrValue.Count;
            buffer.WriteInt32(attrValueCount, Endianness.Big);
            for (int i = 0; i < attrValueCount; i++)
            {
                buffer.WriteByte(AttrValue[i]);
            }
        }

    }
}
