/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 添加好友返回
    /// </summary>
    public class CSFriendAddRsp : IStructure
    {

        public CSFriendAddRsp()
        {
            Ret = 0;
            Friender = new CSFriendInfo();
            RoleDBID = 0;
            NetID = 0;
            Level = 0;
            RoleName = "";
            Online = 0;
            FarmPoint = 0;
            FarmCanBGatheredCount = 0;
            LineId = 0;
        }

        public byte Ret;

        /// <summary>
        /// 好友数据列表
        /// </summary>
        public CSFriendInfo Friender;

        /// <summary>
        /// 好友角色DBID
        /// </summary>
        public ulong RoleDBID;

        /// <summary>
        /// 好友角色NetID
        /// </summary>
        public int NetID;

        /// <summary>
        /// 好友角色的等级
        /// </summary>
        public int Level;

        /// <summary>
        /// 对方角色名
        /// </summary>
        public string RoleName;

        /// <summary>
        /// 是否在线（0或1）
        /// </summary>
        public byte Online;

        /// <summary>
        /// 农场点数
        /// </summary>
        public int FarmPoint;

        /// <summary>
        /// 玩家农场可被采集的剩余次数
        /// </summary>
        public int FarmCanBGatheredCount;

        /// <summary>
        /// 好友所在线
        /// </summary>
        public int LineId;

        public void Write(IBuffer buffer)
        {
            buffer.WriteByte(Ret);
            Friender.Write(buffer);
            buffer.WriteUInt64(RoleDBID, Endianness.Big);
            buffer.WriteInt32(NetID, Endianness.Big);
            buffer.WriteInt32(Level, Endianness.Big);
            buffer.WriteInt32(RoleName.Length + 1, Endianness.Big);
            buffer.WriteCString(RoleName);
            buffer.WriteByte(Online);
            buffer.WriteInt32(FarmPoint, Endianness.Big);
            buffer.WriteInt32(FarmCanBGatheredCount, Endianness.Big);
            buffer.WriteInt32(LineId, Endianness.Big);
        }

    }
}
