/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// GM进入战斗副本请求
    /// </summary>
    public class CSGMEnterInstanceReq : IStructure
    {

        public CSGMEnterInstanceReq()
        {
            LevelID = 0;
            WeatherType = 0;
            TimeType = 0;
        }

        /// <summary>
        /// 关卡ID
        /// </summary>
        public int LevelID;

        /// <summary>
        /// 天气类型
        /// </summary>
        public int WeatherType;

        /// <summary>
        /// 时间类型
        /// </summary>
        public int TimeType;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(LevelID, Endianness.Big);
            buffer.WriteInt32(WeatherType, Endianness.Big);
            buffer.WriteInt32(TimeType, Endianness.Big);
        }

    }
}
