/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 统计项数据
    /// </summary>
    public class CSHunterStarStatData : IStructure
    {

        public CSHunterStarStatData()
        {
            StatType = 0;
            StatTarget = 0;
            StatArg1 = 0;
            StatArg2 = 0;
            StatArg3 = 0;
            StatValue = 0;
        }

        /// <summary>
        /// 统计项类型
        /// </summary>
        public ushort StatType;

        /// <summary>
        /// 统计目标
        /// </summary>
        public uint StatTarget;

        /// <summary>
        /// 统计参数
        /// </summary>
        public uint StatArg1;

        /// <summary>
        /// 统计参数
        /// </summary>
        public uint StatArg2;

        /// <summary>
        /// 统计参数
        /// </summary>
        public uint StatArg3;

        /// <summary>
        /// 统计值
        /// </summary>
        public uint StatValue;

        public void Write(IBuffer buffer)
        {
            buffer.WriteUInt16(StatType, Endianness.Big);
            buffer.WriteUInt32(StatTarget, Endianness.Big);
            buffer.WriteUInt32(StatArg1, Endianness.Big);
            buffer.WriteUInt32(StatArg2, Endianness.Big);
            buffer.WriteUInt32(StatArg3, Endianness.Big);
            buffer.WriteUInt32(StatValue, Endianness.Big);
        }

    }
}
