/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 学习生产配方结果
    /// </summary>
    public class CSManufactureLearnIngredientRsp : IStructure
    {

        public CSManufactureLearnIngredientRsp()
        {
            Ret = 0;
            Reason = 0;
            FormulaID = 0;
        }

        /// <summary>
        /// 返回值，0为成功
        /// </summary>
        public int Ret;

        /// <summary>
        /// 原因1表示正常学习获得，2表示领悟获得
        /// </summary>
        public int Reason;

        /// <summary>
        /// 配方ID
        /// </summary>
        public int FormulaID;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(Ret, Endianness.Big);
            buffer.WriteInt32(Reason, Endianness.Big);
            buffer.WriteInt32(FormulaID, Endianness.Big);
        }

    }
}
