/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 怪物技能同步消息
    /// </summary>
    public class CSMonsterSequenceState : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(CSMonsterSequenceState));

        public CSMonsterSequenceState()
        {
            MonsterID = 0;
            AnimSeqName = "";
            CurTime = 0.0f;
            Location = new CSVec3();
            Rotation = new CSQuat();
        }

        /// <summary>
        /// 怪物ID
        /// </summary>
        public uint MonsterID;

        /// <summary>
        /// 技能name
        /// </summary>
        public string AnimSeqName;

        /// <summary>
        /// 技能时间
        /// </summary>
        public float CurTime;

        /// <summary>
        /// 世界坐标系下的位置
        /// </summary>
        public CSVec3 Location;

        /// <summary>
        /// 朝向
        /// </summary>
        public CSQuat Rotation;

        public void Write(IBuffer buffer)
        {
            buffer.WriteUInt32(MonsterID, Endianness.Big);
            buffer.WriteInt32(AnimSeqName.Length + 1, Endianness.Big);
            buffer.WriteCString(AnimSeqName);
            buffer.WriteFloat(CurTime, Endianness.Big);
            Location.Write(buffer);
            Rotation.Write(buffer);
        }

        public void Read(IBuffer buffer)
        {
            MonsterID = buffer.ReadUInt32(Endianness.Big);
            int AnimSeqNameEntryLen = buffer.ReadInt32(Endianness.Big);
            AnimSeqName = buffer.ReadString(AnimSeqNameEntryLen);
            CurTime = buffer.ReadFloat(Endianness.Big);
            Location.Read(buffer);
            Rotation.Read(buffer);
        }

    }
}
