/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// pet appear notify
    /// </summary>
    public class CSSoulBeastAppearNtf : IStructure
    {

        public CSSoulBeastAppearNtf()
        {
            NetID = 0;
            OwnerID = 0;
            InfoID = 0;
            Pose = new CSQuatT();
            Beast = new List<byte>();
        }

        /// <summary>
        /// logic pet entity id
        /// </summary>
        public int NetID;

        /// <summary>
        /// logic player entity id
        /// </summary>
        public int OwnerID;

        /// <summary>
        /// static data id
        /// </summary>
        public int InfoID;

        /// <summary>
        /// Appear location
        /// </summary>
        public CSQuatT Pose;

        /// <summary>
        /// pet数据
        /// </summary>
        public List<byte> Beast;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(NetID, Endianness.Big);
            buffer.WriteInt32(OwnerID, Endianness.Big);
            buffer.WriteInt32(InfoID, Endianness.Big);
            Pose.Write(buffer);
            int beastCount = (int)Beast.Count;
            buffer.WriteInt32(beastCount, Endianness.Big);
            for (int i = 0; i < beastCount; i++)
            {
                buffer.WriteByte(Beast[i]);
            }
        }

    }
}
