/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 状态Reset
    /// </summary>
    public class CSStateResetInfo : IStructure
    {

        public CSStateResetInfo()
        {
            SyncTime = 0;
            state1 = 0;
            state2 = 0;
            state3 = 0;
            state4 = 0;
            AGState = 0;
        }

        /// <summary>
        /// Reset时间
        /// </summary>
        public long SyncTime;

        /// <summary>
        /// 玩家Stance或者FSM状态
        /// </summary>
        public uint state1;

        /// <summary>
        /// 玩家Stance或者FSM状态
        /// </summary>
        public uint state2;

        /// <summary>
        /// 玩家Stance或者FSM状态
        /// </summary>
        public uint state3;

        /// <summary>
        /// 玩家Stance或者FSM状态
        /// </summary>
        public uint state4;

        /// <summary>
        /// 玩家AG状态
        /// </summary>
        public uint AGState;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt64(SyncTime, Endianness.Big);
            buffer.WriteUInt32(state1, Endianness.Big);
            buffer.WriteUInt32(state2, Endianness.Big);
            buffer.WriteUInt32(state3, Endianness.Big);
            buffer.WriteUInt32(state4, Endianness.Big);
            buffer.WriteUInt32(AGState, Endianness.Big);
        }

    }
}
