/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 队员add/del buff同步
    /// </summary>
    public class CSTeamMemberBuffAddDelNtf : IStructure
    {

        public CSTeamMemberBuffAddDelNtf()
        {
            NetId = 0;
            BuffOp = 0;
            BuffId = 0;
            BuffRetainTime = 0;
            BuffStackCount = 0;
            Dbid = 0;
        }

        /// <summary>
        /// 队员NetID
        /// </summary>
        public uint NetId;

        /// <summary>
        /// Buff 操作（add/del）
        /// </summary>
        public int BuffOp;

        /// <summary>
        /// Buff Id
        /// </summary>
        public int BuffId;

        public int BuffRetainTime;

        public int BuffStackCount;

        /// <summary>
        /// 队员dbid
        /// </summary>
        public ulong Dbid;

        public void Write(IBuffer buffer)
        {
            buffer.WriteUInt32(NetId, Endianness.Big);
            buffer.WriteInt32(BuffOp, Endianness.Big);
            buffer.WriteInt32(BuffId, Endianness.Big);
            buffer.WriteInt32(BuffRetainTime, Endianness.Big);
            buffer.WriteInt32(BuffStackCount, Endianness.Big);
            buffer.WriteUInt64(Dbid, Endianness.Big);
        }

    }
}
