/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.Logging;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 宠物随机信息
    /// </summary>
    public class S2CPetRng : IStructure
    {
        private static readonly ILogger Logger = LogProvider.Logger(typeof(S2CPetRng));

        public S2CPetRng()
        {
            Attrs = new List<byte>();
        }

        /// <summary>
        /// 宠物属性
        /// </summary>
        public List<byte> Attrs;

        public void Write(IBuffer buffer)
        {
            int attrsCount = (int)Attrs.Count;
            buffer.WriteInt32(attrsCount, Endianness.Big);
            for (int i = 0; i < attrsCount; i++)
            {
                buffer.WriteByte(Attrs[i]);
            }
        }

        public void Read(IBuffer buffer)
        {
            Attrs.Clear();
            int attrsCount = buffer.ReadInt32(Endianness.Big);
            for (int i = 0; i < attrsCount; i++)
            {
                byte AttrsEntry = buffer.ReadByte();
                Attrs.Add(AttrsEntry);
            }
        }

    }
}
