/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    /// <summary>
    /// 日常同步
    /// </summary>
    public class S2CSyncDaily : IStructure
    {

        public S2CSyncDaily()
        {
            Daily = new List<short>();
            RefreshTime = 0;
            RefreshLevel = 0;
            CompleteCount = 0;
        }

        /// <summary>
        /// 日常集
        /// </summary>
        public List<short> Daily;

        /// <summary>
        /// 刷新时间
        /// </summary>
        public uint RefreshTime;

        /// <summary>
        /// 刷新等级
        /// </summary>
        public int RefreshLevel;

        /// <summary>
        /// 完成数
        /// </summary>
        public int CompleteCount;

        public void Write(IBuffer buffer)
        {
            short dailyCount = (short)Daily.Count;
            buffer.WriteInt16(dailyCount, Endianness.Big);
            for (int i = 0; i < dailyCount; i++)
            {
                buffer.WriteInt16(Daily[i], Endianness.Big);
            }
            buffer.WriteUInt32(RefreshTime, Endianness.Big);
            buffer.WriteInt32(RefreshLevel, Endianness.Big);
            buffer.WriteInt32(CompleteCount, Endianness.Big);
        }

    }
}
