/*
* This file is part of Arrowgene.MonsterHunterOnline
*
* Arrowgene.MonsterHunterOnline is a server implementation for the game "Monster Hunter Online".
* Copyright (C) 2023-2024 "all contributors"
*
* Github: https://github.com/sebastian-heinz/Arrowgene.MonsterHunterOnline
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published
*  by the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

using System.Collections.Generic;
using Arrowgene.Buffers;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Core;
using Arrowgene.MonsterHunterOnline.Service.CsProto.Enums;

namespace Arrowgene.MonsterHunterOnline.Service.CsProto.Structures
{

    public class ScriptActivityDataButtonEnterLevel : ScriptActivityDataUnion
    {

        public ScriptActivityDataButtonEnterLevel()
        {
            Label = "";
            LevelID = 0;
            EnterMode = 0;
            DataID = 0;
            Condition = "";
        }

        public EScriptActivityDataType Type => EScriptActivityDataType.kScriptActivityDataType_ButtonEnterLevel;

        /// <summary>
        /// 按钮文字
        /// </summary>
        public string Label;

        /// <summary>
        /// 关卡ID
        /// </summary>
        public uint LevelID;

        /// <summary>
        /// 进入方式
        /// </summary>
        public byte EnterMode;

        /// <summary>
        /// 次数统计ID
        /// </summary>
        public byte DataID;

        /// <summary>
        /// 条件
        /// </summary>
        public string Condition;

        public void Write(IBuffer buffer)
        {
            buffer.WriteInt32(Label.Length + 1, Endianness.Big);
            buffer.WriteCString(Label);
            buffer.WriteUInt32(LevelID, Endianness.Big);
            buffer.WriteByte(EnterMode);
            buffer.WriteByte(DataID);
            buffer.WriteInt32(Condition.Length + 1, Endianness.Big);
            buffer.WriteCString(Condition);
        }

    }
}
